# Generated by Django 2.2.2 on 2019-06-05 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DpAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dienstplan', models.IntegerField()),
                ('email_neu', models.IntegerField()),
                ('email_austragen', models.IntegerField()),
                ('email_uebernahme', models.IntegerField()),
                ('email_adminaction', models.IntegerField()),
            ],
            options={
                'db_table': 'dp_admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DpBereitschaft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'dp_bereitschaft',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DpFunktion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('dienstplan', models.IntegerField()),
                ('order', models.IntegerField()),
                ('wachgeld', models.DecimalField(decimal_places=2, max_digits=6)),
                ('wachgeld_art', models.IntegerField()),
                ('wachgeld_kat', models.CharField(blank=True, max_length=2, null=True)),
                ('ical_alarm', models.IntegerField()),
            ],
            options={
                'db_table': 'dp_funktion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DpFunktionsvk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'dp_funktionsVK',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DpMitglieder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('berufer', models.IntegerField()),
                ('steuer', models.IntegerField()),
                ('lastlogin', models.IntegerField()),
                ('login', models.CharField(blank=True, max_length=255, null=True)),
                ('pass_field', models.CharField(blank=True, db_column='pass', max_length=255, null=True)),
                ('newpasshash', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('telefon', models.CharField(blank=True, max_length=255, null=True)),
                ('bemerkung', models.CharField(blank=True, max_length=255, null=True)),
                ('pnr', models.CharField(blank=True, max_length=8, null=True)),
                ('sid', models.CharField(blank=True, max_length=255, null=True)),
                ('startdp', models.IntegerField()),
                ('seeuserdetails', models.IntegerField(blank=True, db_column='seeUserDetails', null=True)),
                ('seestatistics', models.IntegerField(blank=True, db_column='seeStatistics', null=True)),
                ('rightswachbuch', models.IntegerField(blank=True, db_column='rightsWachbuch', null=True)),
                ('tagewachbuch', models.IntegerField(db_column='tageWachbuch')),
                ('wronglogin', models.IntegerField()),
                ('locked', models.IntegerField()),
                ('inactive', models.IntegerField()),
                ('be_login', models.CharField(blank=True, max_length=255, null=True)),
                ('be_pass', models.CharField(blank=True, max_length=255, null=True)),
                ('kvadmin', models.IntegerField()),
                ('ad_user', models.CharField(blank=True, max_length=30, null=True)),
                ('ad_initialpasswort', models.CharField(blank=True, max_length=10, null=True)),
                ('kontodatenvorhanden', models.IntegerField()),
                ('created', models.DateTimeField()),
            ],
            options={
                'db_table': 'dp_mitglieder',
                'managed': False,
            },
        ),
    ]
